name: Validate Documentation

on:
  push:
    branches: [ main, develop ]
    paths: [ './**' ]
  pull_request:
    branches: [ main ]
    paths: [ './**' ]

jobs:
  validate-docsify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install Docsify CLI
      run: npm install -g docsify-cli
    
    - name: Validate Docsify configuration
      run: |
        cd docs
        bash validate-docsify.sh
    
    - name: Test Docsify build
      run: |
        cd docs
        # Test that docsify can serve the documentation
        timeout 10s docsify serve . --port 3000 || true
        echo "Docsify build test completed"
    
    - name: Check for broken links (basic)
      run: |
        cd docs
        # Basic check for common markdown issues
        find . -name "*.md" -exec grep -H "\]\(" {} \; | grep -v "http" | head -20 || true
        echo "Link check completed"
    
    - name: Validate Mermaid diagrams
      run: |
        cd docs
        # Count Mermaid diagrams
        mermaid_count=$(find . -name "*.md" -exec grep -l "```mermaid" {} \; | wc -l)
        echo "Found $mermaid_count files with Mermaid diagrams"
        
        # Check for basic Mermaid syntax
        find . -name "*.md" -exec grep -A 5 "```mermaid" {} \; | head -50 || true
    
    - name: Generate documentation report
      run: |
        cd docs
        echo "# Documentation Validation Report" > validation-report.md
        echo "" >> validation-report.md
        echo "## File Count" >> validation-report.md
        echo "- Markdown files: $(find . -name '*.md' | wc -l)" >> validation-report.md
        echo "- Mermaid diagrams: $(find . -name '*.md' -exec grep -l '```mermaid' {} \; | wc -l)" >> validation-report.md
        echo "- Total directories: $(find . -type d | wc -l)" >> validation-report.md
        echo "" >> validation-report.md
        echo "## Structure" >> validation-report.md
        tree -I '.git' . >> validation-report.md || ls -la >> validation-report.md
        
    - name: Upload validation report
      uses: actions/upload-artifact@v3
      with:
        name: documentation-validation-report
        path: docs/validation-report.md